### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by NofelYaseen** [dragosdmtrsc/bf4#2]
<code>
/home/nyaseen/<b>bf4/backends/analysis/ub/ExplicitUB.cpp</b>: In member function ‘analysis::packet_method_t analysis::PackVisitor::shred(analysis::packet_method_t&&)’:
/home/nyaseen/bf4/backends/analysis/ub/ExplicitUB.cpp:2267:58: error: no matching function for call to ‘apply_visitor(analysis::PackVisitor&, std::remove_reference<boost::variant<analysis::packet_method_t::prepend_var_var_t, analysis::packet_method_t::prepend_var_emit_t, analysis::packet_method_t::extract_t, analysis::packet_method_t::advance_t, analysis::packet_method_t::assign_t, analysis::packet_method_t::zero_t>&>::type)’
     return boost::apply_visitor(*this, std::move(pm.data));
</code>

<br />
<br />
It seems like the issue could be difference in boost library versions. I am currently using boost `1.65.1`.
Can you please tell me the boost version used to make the program?

**Comment by dragosdmtrsc** [comment]
Hi, bf4 works against boost version 1.70.0 - not sure why it wouldn't go against 1.65.
Perhaps before going to the trouble of installing a new boost version, could you please update to the latest commit and check if anything changed?

**Comment by NofelYaseen** [comment]
Updated to the latest commit. 
Also tried on a fresh machine.
Same error.

Ubuntu version: `18.04.5`
Boost version: `1.65.1`
gcc/g++ version: `7.5.0`
z3 version: `4.8.7`
llvm version: `6.0.0`
Thrift version: `0.11.0`
libtool version: `2.4.6`

Cmake was done using:
`cmake -DENABLE_UNIFIED_COMPILATION=OFF ..`

**Comment by dragosdmtrsc** [comment]
in my setup, I am using boost 1.70.0, but now it should also work with older versions of boost

**Comment by NofelYaseen** [comment]
I got it to work on ubuntu16.
